//
//  ContentView.swift
//  TripWise
//
//  Created by Samuel Antonio Mento on 22/09/2026.
//
import Foundation

struct City: Identifiable, Equatable, Codable {
    var id = UUID()
    let name: String
    let country: String
    let imageName: String
    var latitude: Double
    var longitude: Double
    
    var description: String
   
    // BITMASK DEL PAESAGGIO:
    // 1=Città, 2=Campagna, 4=Mare, 8=Montagna, 16=Lago, 32=Deserto, 64=Pianura, 128=Giungla
    var sceneryBitmask: Int64 = 1 // Di default Città (1)
    

    static func == (lhs: City, rhs: City) -> Bool {
        return lhs.name == rhs.name
    }
}

let europeanCitiesData: [Int64: City] = [
    0: City(name: "Butrint", country: "Albania", imageName: "butrint_pic", latitude: 39.7436, longitude: 20.0200, description: "Ancient archaeological site immersed in nature between sea and history.", sceneryBitmask: 5),
    1: City(name: "Tirana", country: "Albania", imageName: "tirana_pic", latitude: 41.3275, longitude: 19.8187, description: "Vibrant and colorful capital, rich in local culture and modern architecture.", sceneryBitmask: 1),
    4: City(name: "Andorra la Vella", country: "Andorra", imageName: "andorra_la_vella_pic", latitude: 42.5063, longitude: 1.5218, description: "Picturesque capital nestled in the peaks of the Pyrenees, ideal for shopping and relaxation.", sceneryBitmask: 9),
    19: City(name: "Garni", country: "Armenia", imageName: "garni_pic", latitude: 40.1147, longitude: 44.7303, description: "Famous for its Hellenistic temple and unique rural landscapes.", sceneryBitmask: 3),
    20: City(name: "Sevan", country: "Armenia", imageName: "sevan_pic", latitude: 40.5539, longitude: 44.9510, description: "Stunning location overlooking the famous high alpine lake.", sceneryBitmask: 16),
    21: City(name: "Yerevan", country: "Armenia", imageName: "yerevan_pic", latitude: 40.1872, longitude: 44.5152, description: "One of the oldest cities in the world, rich in culture and outdoor cafes.", sceneryBitmask: 1),
    38: City(name: "Bregenz", country: "Austria", imageName: "bregenz_pic", latitude: 47.5031, longitude: 9.7471, description: "Elegantly cultural town nestled on the shores of Lake Constance.", sceneryBitmask: 16),
    41: City(name: "Innsbruck", country: "Austria", imageName: "innsbruck_pic", latitude: 47.2692, longitude: 11.4041, description: "Capital of the Alps, a perfect blend of imperial architecture and sports.", sceneryBitmask: 9),
    42: City(name: "Ischgl", country: "Austria", imageName: "ischgl_pic", latitude: 47.0119, longitude: 10.2872, description: "Famous mountain ski resort with legendary slopes and vibrant nightlife.", sceneryBitmask: 8),
    44: City(name: "Klagenfurt", country: "Austria", imageName: "klagenfurt_pic", latitude: 46.6247, longitude: 14.3050, description: "Romantic city bathed by the warm waters of Lake Wörthersee.", sceneryBitmask: 16),
    48: City(name: "Vienna", country: "Austria", imageName: "vienna_pic", latitude: 48.2082, longitude: 16.3738, description: "Majestic capital of music, imperial palaces, and coffeehouse culture.", sceneryBitmask: 1),
    52: City(name: "Baku", country: "Azerbaijan", imageName: "baku_pic", latitude: 40.4093, longitude: 49.8671, description: "Futuristic metropolis overlooking the Caspian Sea, balancing history and modernity.", sceneryBitmask: 5),
    58: City(name: "Brest", country: "Belarus", imageName: "brest_pic", latitude: 52.0976, longitude: 23.7341, description: "Historic border city known for its imposing fortress.", sceneryBitmask: 1),
    59: City(name: "Gomel", country: "Belarus", imageName: "gomel_pic", latitude: 52.4345, longitude: 30.9754, description: "Important cultural center featuring splendid parks and historical palaces.", sceneryBitmask: 1),
    60: City(name: "Grodno", country: "Belarus", imageName: "grodno_pic", latitude: 53.6688, longitude: 23.8213, description: "Fascinating town rich in Gothic and Baroque architecture.", sceneryBitmask: 1),
    61: City(name: "Minsk", country: "Belarus", imageName: "minsk_pic", latitude: 53.9006, longitude: 27.5590, description: "Capital characterized by grand Soviet architecture and broad green avenues.", sceneryBitmask: 1),
    62: City(name: "Vitebsk", country: "Belarus", imageName: "vitebsk_pic", latitude: 55.1927, longitude: 30.2064, description: "Art city tied to painting traditions and historic museums.", sceneryBitmask: 1),
    63: City(name: "Antwerpen", country: "Belgium", imageName: "antwerpen_pic", latitude: 51.2194, longitude: 4.4025, description: "City of fashion, diamonds, and great Flemish masters of art.", sceneryBitmask: 5),
    65: City(name: "Bruges", country: "Belgium", imageName: "bruges_pic", latitude: 51.2093, longitude: 3.2247, description: "Enchanting medieval town crossed by romantic canals.", sceneryBitmask: 1),
    66: City(name: "Brussels", country: "Belgium", imageName: "brussels_pic", latitude: 50.8503, longitude: 4.3517, description: "Heart of Europe, famous for chocolate, comic books, and historic squares.", sceneryBitmask: 1),
    67: City(name: "Dinant", country: "Belgium", imageName: "dinant_pic", latitude: 50.2606, longitude: 4.9122, description: "Picturesque town nestled between rocky cliffs and the Meuse River.", sceneryBitmask: 2),
    69: City(name: "Leuven", country: "Belgium", imageName: "leuven_pic", latitude: 50.8798, longitude: 4.7005, description: "Vibrant university city with a magnificent library and historic breweries.", sceneryBitmask: 1),
    87: City(name: "Banja Luka", country: "Bosnia and Herzegovina", imageName: "banja_luka_pic", latitude: 44.7722, longitude: 17.1910, description: "Green and welcoming spa city along the banks of the Vrbas River.", sceneryBitmask: 1),
    89: City(name: "Mostar", country: "Bosnia and Herzegovina", imageName: "mostar_pic", latitude: 43.3438, longitude: 17.8078, description: "World-famous for its iconic suspended Ottoman bridge.", sceneryBitmask: 9),
    91: City(name: "Sarajevo", country: "Bosnia and Herzegovina", imageName: "sarajevo_pic", latitude: 43.8563, longitude: 18.4131, description: "Crossroads of cultures and religions surrounded by striking mountains.", sceneryBitmask: 9),
    92: City(name: "Trebinje", country: "Bosnia and Herzegovina", imageName: "trebinje_pic", latitude: 42.7110, longitude: 18.3436, description: "Quiet southern town known for its centuries-old plane trees.", sceneryBitmask: 1),
    93: City(name: "Višegrad", country: "Bosnia and Herzegovina", imageName: "višegrad_pic", latitude: 43.7825, longitude: 19.2925, description: "Historic mountain village famous for its UNESCO-listed bridge.", sceneryBitmask: 9),
    117: City(name: "Bansko", country: "Bulgaria", imageName: "bansko_pic", latitude: 41.8383, longitude: 23.4885, description: "The Bulgarian ski capital, amid snowy mountains and traditional lodges.", sceneryBitmask: 8),
    118: City(name: "Plovdiv", country: "Bulgaria", imageName: "plovdiv_pic", latitude: 42.1449, longitude: 24.7503, description: "Ancient art city featuring a magnificent Roman theater and old quarter.", sceneryBitmask: 1),
    119: City(name: "Sofia", country: "Bulgaria", imageName: "sofia_pic", latitude: 42.6977, longitude: 23.3219, description: "Dynamic capital at the foot of the majestic Vitosha mountain.", sceneryBitmask: 9),
    120: City(name: "Varna", country: "Bulgaria", imageName: "varna_pic", latitude: 43.2046, longitude: 27.9105, description: "Bulgaria's seaside capital on the Black Sea, featuring beaches and parks.", sceneryBitmask: 5),
    183: City(name: "Hvar", country: "Croatia", imageName: "hvar_pic", latitude: 43.1729, longitude: 16.4412, description: "Sun-drenched Croatian island, famous for lavender fields and nightlife.", sceneryBitmask: 5),
    188: City(name: "Šibenik", country: "Croatia", imageName: "šibenik_pic", latitude: 43.7314, longitude: 15.8936, description: "Stunning coastal city with stone cathedrals and sea fortresses.", sceneryBitmask: 5),
    189: City(name: "Split", country: "Split_pic", imageName: "split_pic", latitude: 43.5081, longitude: 16.4402, description: "Vibrant harbor with a Roman heart enclosed within Diocletian's Palace.", sceneryBitmask: 5),
    190: City(name: "Supetar", country: "Supetar_pic", imageName: "supetar_pic", latitude: 43.3844, longitude: 16.5562, description: "Peaceful seaside village on the island of Brač.", sceneryBitmask: 5),
    193: City(name: "Zadar", country: "Croatia", imageName: "zadar_pic", latitude: 44.1194, longitude: 15.2314, description: "Historic seaside city famous for the sea organ and unique sunsets.", sceneryBitmask: 5),
    203: City(name: "Famagusta", country: "Cyprus", imageName: "famagusta_pic", latitude: 35.1149, longitude: 33.9396, description: "Coastal city boasting massive medieval walls and golden beaches.", sceneryBitmask: 5),
    204: City(name: "Larnaca", country: "Cyprus", imageName: "larnaca_pic", latitude: 34.9115, longitude: 33.6276, description: "Relaxing seaside resort lined with palm trees and a scenic promenade.", sceneryBitmask: 5),
    205: City(name: "Limassol", country: "Cyprus", imageName: "limassol_pic", latitude: 34.6786, longitude: 33.0413, description: "Modern coastal city featuring medieval castles and lively nightlife.", sceneryBitmask: 5),
    206: City(name: "Nicosia", country: "Cyprus", imageName: "nicosia_pic", latitude: 35.1856, longitude: 33.3823, description: "The world's last divided capital, rich in history and traditions.", sceneryBitmask: 1),
    207: City(name: "Paphos", country: "Cyprus", imageName: "paphos_pic", latitude: 34.7720, longitude: 32.4297, description: "Legendary coastal resort linked to the myth of Aphrodite and ancient mosaics.", sceneryBitmask: 5),
    208: City(name: "Brno", country: "Czech Republic", imageName: "brno_pic", latitude: 49.1951, longitude: 16.6068, description: "Important Czech cultural center with functionalist architecture and castles.", sceneryBitmask: 1),
    209: City(name: "Český Krumlov", country: "Czech Republic", imageName: "český_krumlov_pic", latitude: 48.8127, longitude: 14.3175, description: "Fairy-tale medieval town looped around the Vltava River.", sceneryBitmask: 2),
    210: City(name: "Karlovy Vary", country: "Czech Republic", imageName: "karlovy_vary_pic", latitude: 50.2319, longitude: 12.8715, description: "Famous spa town surrounded by hills and historic colonnades.", sceneryBitmask: 9),
    211: City(name: "Kutná Hora", country: "Czech Republic", imageName: "kutná_hora_pic", latitude: 49.9506, longitude: 15.2678, description: "Historic mining town known for its Gothic marvels.", sceneryBitmask: 1),
    212: City(name: "Prague", country: "Czech Republic", imageName: "prague_pic", latitude: 50.0755, longitude: 14.4378, description: "The city of a hundred spires, magical and rich in Gothic charm.", sceneryBitmask: 1),
    215: City(name: "Billund", country: "Denmark", imageName: "billund_pic", latitude: 55.7313, longitude: 9.1123, description: "The birthplace of LEGO, perfect for families and fun.", sceneryBitmask: 2),
    216: City(name: "Copenhagen", country: "Denmark", imageName: "copenhagen_pic", latitude: 55.6761, longitude: 12.5683, description: "Scandinavian design capital featuring picturesque canals and sustainable living.", sceneryBitmask: 5),
    217: City(name: "Elsinore", country: "Denmark", imageName: "elsinore_pic", latitude: 56.0361, longitude: 12.6136, description: "Celebrated for Shakespeare's majestic seaside castle of Hamlet.", sceneryBitmask: 5),
    219: City(name: "Ribe", country: "Denmark", imageName: "ribe_pic", latitude: 55.3280, longitude: 8.7610, description: "Denmark's oldest town, steeped in Viking atmosphere.", sceneryBitmask: 2),
    221: City(name: "Skagen", country: "Denmark", imageName: "skagen_pic", latitude: 57.7209, longitude: 10.5839, description: "A striking meeting point of two seas and a renowned artists' retreat.", sceneryBitmask: 5),
    256: City(name: "Haapsalu", country: "Estonia", imageName: "haapsalu_pic", latitude: 58.9431, longitude: 23.5414, description: "Romantic spa town on the Baltic Sea with a bishop's castle.", sceneryBitmask: 5),
    257: City(name: "Tallinn", country: "Estonia", imageName: "tallinn_pic", latitude: 59.4370, longitude: 24.7536, description: "Incredible fortified medieval old town overlooking the gulf.", sceneryBitmask: 5),
    258: City(name: "Tartu", country: "Estonia", imageName: "tartu_pic", latitude: 58.3780, longitude: 26.7290, description: "Intellectual and ancient Estonian university city.", sceneryBitmask: 1),
    263: City(name: "Kemi", country: "Finland", imageName: "kemi_pic", latitude: 65.7364, longitude: 24.5637, description: "Famous for extreme winter experiences and the ice castle.", sceneryBitmask: 5),
    265: City(name: "Rovaniemi", country: "Finland", imageName: "rovaniemi_pic", latitude: 66.5039, longitude: 25.7294, description: "The official residence of Santa Claus in the heart of Lapland.", sceneryBitmask: 8),
    267: City(name: "Helsinki", country: "Finland", imageName: "helsinki_pic", latitude: 60.1695, longitude: 24.9354, description: "Modern Nordic capital blending islands, design, and neoclassical architecture.", sceneryBitmask: 5),
    269: City(name: "Savonlinna", country: "Finland", imageName: "savonlinna_pic", latitude: 61.8687, longitude: 28.8876, description: "Charming lakeside town famous for its medieval water castle.", sceneryBitmask: 16),
    270: City(name: "Turku", country: "Finland", imageName: "turku_pic", latitude: 60.4518, longitude: 22.2666, description: "Finland's ancient capital resting along the mouth of the Aura River.", sceneryBitmask: 5),
    272: City(name: "Bastia", country: "France", imageName: "bastia_pic", latitude: 42.6973, longitude: 9.4509, description: "Lively Corsican port nestled between crystal-clear sea and historic alleys.", sceneryBitmask: 5),
    281: City(name: "Antibes", country: "France", imageName: "antibes_pic", latitude: 43.5804, longitude: 7.1251, description: "French Riviera gem featuring luxury yachts and the Picasso Museum.", sceneryBitmask: 5),
    283: City(name: "Avignon", country: "France", imageName: "avignon_pic", latitude: 43.9493, longitude: 4.8055, description: "The City of Popes in Provence, rich in history and theaters.", sceneryBitmask: 1),
    292: City(name: "Le Mont-Saint-Michel", country: "France", imageName: "le_mont_saint_michel_pic", latitude: 48.6361, longitude: -1.5115, description: "Spectacular rocky tidal island crowned by a Gothic abbey.", sceneryBitmask: 5),
    305: City(name: "Versailles", country: "France", imageName: "versailles_pic", latitude: 48.8014, longitude: 2.1301, description: "Globally celebrated for its lavish royal palace and grand gardens.", sceneryBitmask: 1),
    306: City(name: "Batumi", country: "Georgia", imageName: "batumi_pic", latitude: 41.6168, longitude: 41.6367, description: "Modern Georgian seaside resort on the Black Sea.", sceneryBitmask: 5),
    307: City(name: "Sighnaghi", country: "Georgia", imageName: "sighnaghi_pic", latitude: 41.6190, longitude: 45.9220, description: "Romantic wine town situated in the stunning Kakheti region.", sceneryBitmask: 2),
    308: City(name: "Tbilisi", country: "Georgia", imageName: "tbilisi_pic", latitude: 41.7151, longitude: 44.8271, description: "Georgian capital featuring colorful houses, sulfur baths, and fortresses.", sceneryBitmask: 1),
    313: City(name: "Berlin", country: "Germany", imageName: "berlin_pic", latitude: 52.5200, longitude: 13.4050, description: "Vanguard European metropolis, underground culture, and immense history.", sceneryBitmask: 1),
    316: City(name: "Cologne", country: "Germany", imageName: "cologne_pic", latitude: 50.9375, longitude: 6.9603, description: "Famous for its imposing Gothic cathedral overlooking the Rhine.", sceneryBitmask: 1),
    320: City(name: "Frankfurt am Main", country: "Germany", imageName: "frankfurt_am_main_pic", latitude: 50.1109, longitude: 8.6821, description: "German financial heart with modern skyscrapers and a reconstructed old town.", sceneryBitmask: 1),
    333: City(name: "Münster", country: "Germany", imageName: "münster_pic", latitude: 51.9607, longitude: 7.6261, description: "Splendid bicycle-friendly university city.", sceneryBitmask: 1),
    339: City(name: "Rüdesheim am Rhein", country: "Germany", imageName: "rüdesheim_am_rhein_pic", latitude: 49.9806, longitude: 7.9250, description: "Picturesque wine-growing village along the romantic Rhine valley.", sceneryBitmask: 2),
    344: City(name: "Heraklion", country: "Greece", imageName: "heraklion_pic", latitude: 35.3387, longitude: 25.1442, description: "Lively Cretan port close to the ruins of the historic Palace of Knossos.", sceneryBitmask: 5),
    350: City(name: "Corinth", country: "Greece", imageName: "corinth_pic", latitude: 37.9386, longitude: 22.9320, description: "Important historic junction between two seas and celebrated archaeological site.", sceneryBitmask: 5),
    357: City(name: "Mykonos", country: "Greece", imageName: "mykonos_pic", latitude: 37.4467, longitude: 25.3289, description: "Famous Cycladic island for crystal beaches and exclusive nightlife.", sceneryBitmask: 5),
    359: City(name: "Naxos", country: "Greece", imageName: "naxos_pic", latitude: 37.1056, longitude: 25.3761, description: "Authentic Greek island blending sandy beaches and ancient marble temples.", sceneryBitmask: 5),
    360: City(name: "Olympia", country: "Greece", imageName: "olympia_pic", latitude: 37.6447, longitude: 21.6265, description: "Birthplace of the ancient Olympic games set in lush greenery.", sceneryBitmask: 2),
    368: City(name: "Nuuk", country: "Greenland (Denmark)", imageName: "nuuk_pic", latitude: 64.1814, longitude: -51.6941, description: "Fascinating Greenlandic capital nestled among spectacular fjords and arctic nature.", sceneryBitmask: 5),
    369: City(name: "Qaqortoq", country: "Greenland (Denmark)", imageName: "qaqortoq_pic", latitude: 60.7167, longitude: -46.0333, description: "Picturesque colorful town in southern Greenland.", sceneryBitmask: 5),
    377: City(name: "Budapest", country: "Hungary", imageName: "budapest_pic", latitude: 47.4979, longitude: 19.0402, description: "The Pearl of the Danube, celebrated for thermal baths and the imposing parliament.", sceneryBitmask: 1),
    378: City(name: "Eger", country: "Hungary", imageName: "eger_pic", latitude: 47.9026, longitude: 20.3733, description: "Baroque town known for historic castles and excellent red wines.", sceneryBitmask: 2),
    380: City(name: "Pécs", country: "Hungary", imageName: "pécs_pic", latitude: 46.0727, longitude: 18.2323, description: "Mediterranean city rich in early Christian monuments and museums.", sceneryBitmask: 1),
    381: City(name: "Sopron", country: "Hungary", imageName: "sopron_pic", latitude: 47.6833, longitude: 16.5833, description: "Historic border town featuring a well-preserved medieval center.", sceneryBitmask: 2),
    382: City(name: "Szentendre", country: "Hungary", imageName: "szentendre_pic", latitude: 47.6694, longitude: 19.0761, description: "Vibrant artists' town overlooking the Danube bend.", sceneryBitmask: 2),
    383: City(name: "Akureyri", country: "Iceland", imageName: "akureyri_pic", latitude: 65.6835, longitude: -18.1105, description: "Capital of northern Iceland, surrounded by mountains and fjords.", sceneryBitmask: 13),
    384: City(name: "Höfn", country: "Iceland", imageName: "höfn_pic", latitude: 64.2500, longitude: -15.2082, description: "Fishing port nestled at the foot of eastern Iceland's grand glaciers.", sceneryBitmask: 13),
    386: City(name: "Keflavik", country: "Iceland", imageName: "keflavik_pic", latitude: 64.0000, longitude: -22.5629, description: "Icelandic maritime gateway close to volcanic wonders.", sceneryBitmask: 5),
    387: City(name: "Reykjavik", country: "Iceland", imageName: "reykjavik_pic", latitude: 64.1466, longitude: -21.9426, description: "Creative, colorful Icelandic capital close to geysers and hot springs.", sceneryBitmask: 5),
    389: City(name: "Vík í Mýrdal", country: "Iceland", imageName: "vík_í_mýrdal_pic", latitude: 63.4186, longitude: -19.0060, description: "Famous for its black sand beaches and basalt sea stacks.", sceneryBitmask: 13),
    410: City(name: "Dingle", country: "Ireland", imageName: "dingle_pic", latitude: 52.1408, longitude: -10.2640, description: "Stunning Irish coastal village amid cliffs and traditional music.", sceneryBitmask: 5),
    411: City(name: "Dublin", country: "Ireland", imageName: "dublin_pic", latitude: 53.3498, longitude: -6.2603, description: "Welcoming Irish capital famous for historic pubs and literature.", sceneryBitmask: 5),
    412: City(name: "Gaillimh", country: "Ireland", imageName: "gaillimh_pic", latitude: 53.2707, longitude: -9.0568, description: "Vibrant cultural city on Ireland's western coast.", sceneryBitmask: 5),
    413: City(name: "Kilkenny", country: "Ireland", imageName: "kilkenny_pic", latitude: 52.6541, longitude: -7.2448, description: "Elegantly medieval town known for its grey stone castle.", sceneryBitmask: 2),
    415: City(name: "Liscannor", country: "Ireland", imageName: "liscannor_pic", latitude: 52.9388, longitude: -9.3972, description: "Close to the impressive and dizzying Cliffs of Moher.", sceneryBitmask: 5),
    433: City(name: "Amalfi", country: "Italy", imageName: "amalfi_pic", latitude: 40.6333, longitude: 14.6029, description: "Pearl of the Campanian coast among sheer cliffs and blue sea.", sceneryBitmask: 13),
    435: City(name: "Brindisi", country: "Italy", imageName: "brindisi_pic", latitude: 40.6327, longitude: 17.9418, description: "Historic Apulian port serving as a gateway to the East.", sceneryBitmask: 5),
    437: City(name: "Florence", country: "Italy", imageName: "florence_pic", latitude: 43.7696, longitude: 11.2558, description: "Cradle of the Italian Renaissance, a treasure chest of priceless art.", sceneryBitmask: 65),
    448: City(name: "Pompei", country: "Italy", imageName: "pompei_pic", latitude: 40.7512, longitude: 14.4869, description: "Extraordinary Roman archaeological site frozen by the eruption of Vesuvius.", sceneryBitmask: 1),
    452: City(name: "Rome", country: "Italy", imageName: "rome_pic", latitude: 41.9028, longitude: 12.4964, description: "The Eternal City, an open-air museum balancing millenary history and la dolce vita.", sceneryBitmask: 1),
    490: City(name: "Jaunmārupe", country: "Latvia", imageName: "jaunmārupe_pic", latitude: 56.8841, longitude: 23.9576, description: "Peaceful green area near the Latvian capital.", sceneryBitmask: 2),
    491: City(name: "Jurmala", country: "Latvia", imageName: "jurmala_pic", latitude: 56.9680, longitude: 23.7704, description: "Famous Latvian seaside resort known for its wooden villas.", sceneryBitmask: 5),
    492: City(name: "Riga", country: "Latvia", imageName: "riga_pic", latitude: 56.9496, longitude: 24.1052, description: "Splendid Baltic capital celebrated for Art Nouveau architectural masterpieces.", sceneryBitmask: 5),
    493: City(name: "Skulte", country: "Latvia", imageName: "skulte_pic", latitude: 57.3195, longitude: 24.4539, description: "Quiet Latvian port and coastal village.", sceneryBitmask: 5),
    494: City(name: "Vecrīga", country: "Latvia", imageName: "vecrīga_pic", latitude: 56.9490, longitude: 24.1070, description: "The historic medieval core of the Latvian capital.", sceneryBitmask: 5),
    499: City(name: "Vaduz", country: "Liechtenstein", imageName: "vaduz_pic", latitude: 47.1410, longitude: 9.5209, description: "Alpine capital dominated by a fairytale princely castle.", sceneryBitmask: 9),
    500: City(name: "Kaunas", country: "Lithuania", imageName: "kaunas_pic", latitude: 54.8985, longitude: 23.9036, description: "Vibrant Lithuanian cultural center with modernist architecture.", sceneryBitmask: 1),
    501: City(name: "Kernave", country: "Lithuania", imageName: "kernave_pic", latitude: 54.8833, longitude: 24.8167, description: "Historic archaeological area featuring evocative hill forts.", sceneryBitmask: 2),
    503: City(name: "Neringa", country: "Lithuania", imageName: "neringa_pic", latitude: 55.3082, longitude: 21.0069, description: "Spectacular UNESCO-protected sand dune peninsula.", sceneryBitmask: 5),
    504: City(name: "Palanga", country: "Lithuania", imageName: "palanga_pic", latitude: 55.9213, longitude: 21.0639, description: "The summer capital of the Lithuanian coast on the Baltic Sea.", sceneryBitmask: 5),
    505: City(name: "Vilnius", country: "Lithuania", imageName: "vilnius_pic", latitude: 54.6872, longitude: 25.2797, description: "Fascinating Baltic capital with a Baroque and bohemian center.", sceneryBitmask: 1),
    506: City(name: "Luxembourg", country: "Luxembourg", imageName: "luxembourg_pic", latitude: 49.6116, longitude: 6.1319, description: "European fortress city featuring imposing fortifications and green valleys.", sceneryBitmask: 1),
    514: City(name: "Rabat", country: "Malta", imageName: "rabat_pic", latitude: 35.8815, longitude: 14.3987, description: "Historic Maltese village rich in catacombs and ancient charm.", sceneryBitmask: 5),
    515: City(name: "Valletta", country: "Malta", imageName: "valletta_pic", latitude: 35.8997, longitude: 14.5147, description: "Majestic fortified Baroque capital overlooking the Mediterranean.", sceneryBitmask: 5),
    540: City(name: "Chisinau", country: "Moldova", imageName: "chisinau_pic", latitude: 47.0105, longitude: 28.8638, description: "Green Moldovan capital surrounded by parks and wineries.", sceneryBitmask: 1),
    541: City(name: "Monaco", country: "Monaco", imageName: "monaco_pic", latitude: 43.7384, longitude: 7.4246, description: "Luxurious principality blending casinos, yachts, and Mediterranean cliffs.", sceneryBitmask: 13),
    542: City(name: "Budva", country: "Montenegro", imageName: "budva_pic", latitude: 42.2911, longitude: 18.8403, description: "Splendid Adriatic coastal town featuring beaches and a medieval old town.", sceneryBitmask: 13),
    543: City(name: "Herceg-Novi", country: "Montenegro", imageName: "herceg_novi_pic", latitude: 42.4531, longitude: 18.5375, description: "Garden city at the entrance of the spectacular Bay of Kotor.", sceneryBitmask: 13),
    544: City(name: "Kotor", country: "Montenegro", imageName: "kotor_pic", latitude: 42.4247, longitude: 18.7712, description: "Spectacular medieval town guarded by steep mountains and blue bays.", sceneryBitmask: 13),
    545: City(name: "Podgorica", country: "Montenegro", imageName: "podgorica_pic", latitude: 42.4411, longitude: 19.2636, description: "Montenegrin capital immersed in river valleys and parks.", sceneryBitmask: 1),
    546: City(name: "Tivat", country: "Montenegro", imageName: "tivat_pic", latitude: 42.4364, longitude: 18.6311, description: "Modern seaside resort boasting an exclusive marina.", sceneryBitmask: 13),
    567: City(name: "Alkmaar", country: "Netherlands", imageName: "alkmaar_pic", latitude: 52.6324, longitude: 4.7534, description: "World-famous for its historic cheese market.", sceneryBitmask: 5),
    568: City(name: "Amsterdam", country: "Netherlands", imageName: "amsterdam_pic", latitude: 52.3676, longitude: 4.9041, description: "The Venice of the North, defined by canals, legendary museums, and bicycles.", sceneryBitmask: 65),
    569: City(name: "Delft", country: "Netherlands", imageName: "delft_pic", latitude: 52.0116, longitude: 4.3571, description: "Characteristic Dutch city famous for blue pottery and canals.", sceneryBitmask: 65),
    574: City(name: "Haarlem", country: "Netherlands", imageName: "haarlem_pic", latitude: 52.3874, longitude: 4.6462, description: "Elegant town rich in historic courtyards and art museums.", sceneryBitmask: 65),
    579: City(name: "Utrecht", country: "Netherlands", imageName: "delft_pic", latitude: 52.0907, longitude: 5.1214, description: "Vibrant university city featuring unique two-level canals.", sceneryBitmask: 65),
    598: City(name: "Geiranger", country: "Norway", imageName: "geiranger_pic", latitude: 62.1015, longitude: 7.2059, description: "Heart of the Norwegian fjords, among majestic waterfalls and sheer cliffs.", sceneryBitmask: 13),
    599: City(name: "Kristiansand", country: "Norway", imageName: "kristiansand_pic", latitude: 58.1599, longitude: 8.0182, description: "Sunny coastal town in southern Norway.", sceneryBitmask: 5),
    601: City(name: "Oslo", country: "Norway", imageName: "oslo_pic", latitude: 59.9139, longitude: 10.7522, description: "Norwegian capital set between a fjord, avant-garde museums, and lush forests.", sceneryBitmask: 13),
    602: City(name: "Stavanger", country: "Norway", imageName: "stavanger_pic", latitude: 58.9699, longitude: 5.7331, description: "Historic Norwegian port and starting point for spectacular hikes.", sceneryBitmask: 13),
    604: City(name: "Trondheim", country: "Norway", imageName: "trondheim_pic", latitude: 63.4305, longitude: 10.3951, description: "Historic Norwegian city famous for its cathedral and colorful waterfront houses.", sceneryBitmask: 13),
    642: City(name: "Krakow", country: "Poland", imageName: "krakow_pic", latitude: 50.0647, longitude: 19.9450, description: "Magnificent Polish art city featuring a massive medieval square.", sceneryBitmask: 1),
    646: City(name: "Sopot", country: "Poland", imageName: "sopot_pic", latitude: 54.4416, longitude: 18.5601, description: "Celebrated Polish seaside resort on the Baltic Sea with the longest wooden pier.", sceneryBitmask: 5),
    647: City(name: "Szczecin", country: "Poland", imageName: "szczecin_pic", latitude: 53.4285, longitude: 14.5528, description: "Important Baltic Polish port rich in parks and castles.", sceneryBitmask: 5),
    648: City(name: "Warsaw", country: "Poland", imageName: "warsaw_pic", latitude: 52.2297, longitude: 21.0122, description: "Resilient and modern Polish capital with a meticulously rebuilt old town.", sceneryBitmask: 1),
    649: City(name: "Wola", country: "Poland", imageName: "wola_pic", latitude: 52.2374, longitude: 20.9616, description: "Dynamic Warsaw district balancing urban history and modernity.", sceneryBitmask: 1),
    658: City(name: "Cascais", country: "Portugal", imageName: "cascais_pic", latitude: 38.6970, longitude: -9.4223, description: "Elegant seaside resort near Lisbon, a historic refuge for nobles and artists.", sceneryBitmask: 5),
    659: City(name: "Coimbra", country: "Portugal", imageName: "coimbra_pic", latitude: 40.2056, longitude: -8.4195, description: "Historic and prestigious Portuguese university city.", sceneryBitmask: 2),
    661: City(name: "Faro", country: "Portugal", imageName: "faro_pic", latitude: 37.0194, longitude: -7.9322, description: "Gateway to the Algarve, nestled between protected lagoons and historic walls.", sceneryBitmask: 5),
    664: City(name: "Porto", country: "Portugal", imageName: "porto_pic", latitude: 41.1579, longitude: -8.6291, description: "Famous for port wine, iron bridges, and houses along the Douro River.", sceneryBitmask: 5),
    665: City(name: "Sintra", country: "Portugal", imageName: "sintra_pic", latitude: 38.8029, longitude: -9.3817, description: "Fairytale hill town surrounded by colorful palaces and lush parks.", sceneryBitmask: 9),
    668: City(name: "Bucharest", country: "Romania", imageName: "bucharest_pic", latitude: 44.4268, longitude: 26.1025, description: "Vibrant Romanian capital known for monumental architecture and nightlife.", sceneryBitmask: 65),
    669: City(name: "Cluj-Napoca", country: "Romania", imageName: "cluj_napoca_pic", latitude: 46.7712, longitude: 23.6236, description: "Lively cultural center of Transylvania rich in universities and history.", sceneryBitmask: 2),
    671: City(name: "Oradea", country: "Romania", imageName: "oradea_pic", latitude: 47.0465, longitude: 21.9189, description: "Elegant art city known for its stunning Art Nouveau buildings.", sceneryBitmask: 65),
    672: City(name: "Sibiu", country: "Romania", imageName: "sibiu_pic", latitude: 45.7983, longitude: 24.1256, description: "Historic Saxon city in Transylvania with atmospheric squares.", sceneryBitmask: 9),
    674: City(name: "Sinaia", country: "Romania", imageName: "sinaia_pic", latitude: 45.3500, longitude: 25.5500, description: "Famous mountain resort in the Carpathians featuring the royal Peleș Castle.", sceneryBitmask: 8),
    678: City(name: "Kazan", country: "Russia", imageName: "kazan_pic", latitude: 55.7963, longitude: 49.1088, description: "Fascinating cultural melting pot centered around an imposing Kremlin.", sceneryBitmask: 1),
    679: City(name: "Moscow", country: "Russia", imageName: "moscow_pic", latitude: 55.7558, longitude: 37.6173, description: "Monumental Russian capital featuring Red Square and colorful domes.", sceneryBitmask: 1),
    680: City(name: "Nizhny Novgorod", country: "Russia", imageName: "nizhny_novgorod_pic", latitude: 56.3269, longitude: 44.0059, description: "Historic commercial and cultural hub on the banks of the Volga River.", sceneryBitmask: 1),
    681: City(name: "Saint Petersburg", country: "Russia", imageName: "saint_petersburg_pic", latitude: 59.9311, longitude: 30.3609, description: "The Venice of Northern Russia, an imperial capital of palaces and canals.", sceneryBitmask: 5),
    683: City(name: "Veliky Novgorod", country: "Russia", imageName: "veliky_novgorod_pic", latitude: 58.5256, longitude: 31.2742, description: "Ancient Russian city rich in monasteries near the lake.", sceneryBitmask: 16),
    688: City(name: "San Marino", country: "San Marino", imageName: "san_marino_pic", latitude: 43.9424, longitude: 12.4578, description: "Ancient republic perched atop Mount Titano with panoramic towers.", sceneryBitmask: 9),
    696: City(name: "Belgrade", country: "Serbia", imageName: "belgrade_pic", latitude: 44.7866, longitude: 20.4489, description: "Dynamic Serbian capital at the confluence of major rivers.", sceneryBitmask: 65),
    697: City(name: "Kopaonik", country: "Serbia", imageName: "kopaonik_pic", latitude: 43.2863, longitude: 20.8103, description: "The primary ski and mountain resort in Serbia.", sceneryBitmask: 8),
    699: City(name: "Novi Sad", country: "Serbia", imageName: "novi_sad_pic", latitude: 45.2671, longitude: 19.8335, description: "Relaxing cultural city on the Danube with a spectacular fortress.", sceneryBitmask: 65),
    700: City(name: "Stari Grad", country: "Serbia", imageName: "stari_grad_pic", latitude: 44.8183, longitude: 20.4560, description: "The historic and beating heart of the Serbian capital.", sceneryBitmask: 1),
    702: City(name: "Zlatibor", country: "Serbia", imageName: "zlatibor_pic", latitude: 43.7258, longitude: 19.6989, description: "Renowned mountain and wellness tourism resort.", sceneryBitmask: 8),
    705: City(name: "Bratislava", country: "Slovakia", imageName: "bratislava_pic", latitude: 48.1486, longitude: 17.1077, description: "Welcoming Slovak capital overlooking the Danube.", sceneryBitmask: 65),
    707: City(name: "Poprad", country: "Poprad_pic", imageName: "poprad_pic", latitude: 49.0560, longitude: 20.3008, description: "Gateway to the dramatic peaks of the High Tatras.", sceneryBitmask: 8),
    709: City(name: "Bovec", country: "Slovenia", imageName: "bovec_pic", latitude: 46.3376, longitude: 13.5521, description: "Slovenian alpine paradise for outdoor sports and emerald rivers.", sceneryBitmask: 8),
    710: City(name: "Koper", country: "Slovenia", imageName: "koper_pic", latitude: 45.5481, longitude: 13.7302, description: "Slovenia's main historic coastal port.", sceneryBitmask: 5),
    712: City(name: "Maribor", country: "Slovenia", imageName: "maribor_pic", latitude: 46.5547, longitude: 15.6459, description: "Home to the world's oldest grapevine in northern Slovenia.", sceneryBitmask: 2),
    713: City(name: "Novo Mesto", country: "Slovenia", imageName: "novo_mesto_pic", latitude: 45.8011, longitude: 15.1710, description: "Green Slovenian town along the bend of the Krka River.", sceneryBitmask: 2),
    715: City(name: "Postojna", country: "Slovenia", imageName: "postojna_pic", latitude: 45.7758, longitude: 14.2153, description: "Famous for its spectacular subterranean karst caves.", sceneryBitmask: 8),
    727: City(name: "Palma", country: "Spain", imageName: "palma_pic", latitude: 39.5696, longitude: 2.6502, description: "Splendid Majorcan capital blending Gothic cathedrals and sea.", sceneryBitmask: 5),
    736: City(name: "Burgos", country: "Spain", imageName: "burgos_pic", latitude: 42.3439, longitude: -3.6969, description: "Historic stop along the Camino de Santiago featuring a unique Gothic cathedral.", sceneryBitmask: 65),
    745: City(name: "Madrid", country: "Spain", imageName: "madrid_pic", latitude: 40.4168, longitude: -3.7038, description: "Vibrant Spanish capital boasting world-class art museums and nightlife.", sceneryBitmask: 65),
    751: City(name: "Santiago de Compostela", country: "Spain", imageName: "santiago_de_compostela_pic", latitude: 42.8805, longitude: -8.5457, description: "Millennial pilgrimage destination with a mystical charm in Galicia.", sceneryBitmask: 2),
    756: City(name: "Valencia", country: "Spain", imageName: "valencia_pic", latitude: 39.4699, longitude: -0.3763, description: "Sunny Mediterranean city uniting futuristic architecture and beaches.", sceneryBitmask: 5),
    769: City(name: "Gothenburg", country: "Sweden", imageName: "gothenburg_pic", latitude: 57.7089, longitude: 11.9746, description: "Welcoming Swedish port famous for canals and seafood cuisine.", sceneryBitmask: 5),
    770: City(name: "Kiruna", country: "Sweden", imageName: "kiruna_pic", latitude: 67.8558, longitude: 20.2253, description: "Arctic mining town in northern Sweden, ideal for viewing the northern lights.", sceneryBitmask: 8),
    773: City(name: "Stockholm", country: "Sweden", imageName: "stockholm_pic", latitude: 59.3293, longitude: 18.0686, description: "Elegant Swedish capital built across an archipelago of islands.", sceneryBitmask: 5),
    774: City(name: "Uppsala", country: "Sweden", imageName: "uppsala_pic", latitude: 59.8586, longitude: 17.6389, description: "Historic Swedish university city rich in Viking traditions.", sceneryBitmask: 65),
    775: City(name: "Visby", country: "Sweden", imageName: "visby_pic", latitude: 57.6348, longitude: 18.2948, description: "Incredible medieval Hanseatic town on the island of Gotland.", sceneryBitmask: 5),
    776: City(name: "Basel", country: "Switzerland", imageName: "basel_pic", latitude: 47.5596, longitude: 7.5886, description: "Swiss capital of contemporary art along the Rhine River.", sceneryBitmask: 1),
    779: City(name: "Geneva", country: "Switzerland", imageName: "geneva_pic", latitude: 46.2044, longitude: 6.1432, description: "International and elegant city overlooking the lake and close to the Alps.", sceneryBitmask: 18),
    781: City(name: "Interlaken", country: "Switzerland", imageName: "interlaken_pic", latitude: 46.6863, longitude: 7.8632, description: "Swiss adventure capital between alpine lakes and iconic mountains.", sceneryBitmask: 24),
    784: City(name: "Lugano", country: "Switzerland", imageName: "lugano_pic", latitude: 46.0037, longitude: 8.9511, description: "Splendid Swiss town with a Mediterranean climate and stunning lakes.", sceneryBitmask: 24),
    785: City(name: "Luzern", country: "Switzerland", imageName: "luzern_pic", latitude: 47.0502, longitude: 8.3093, description: "Picturesque Swiss town featuring medieval covered bridges and an alpine lake.", sceneryBitmask: 24),
    808: City(name: "Port of Spain", country: "Trinidad and Tobago", imageName: "port_of_spain_pic", latitude: 10.6549, longitude: -61.5019, description: "Vibrant Caribbean capital famous for carnival and tropical rhythms.", sceneryBitmask: 5),
    818: City(name: "Bodrum", country: "Turkey", imageName: "bodrum_pic", latitude: 37.0344, longitude: 27.4305, description: "Popular Turkish resort on the Aegean Sea among castles and turquoise water.", sceneryBitmask: 5),
    819: City(name: "Ephesus", country: "Turkey", imageName: "ephesus_pic", latitude: 37.9409, longitude: 27.3411, description: "Extraordinary site of ancient ruins in Asia Minor.", sceneryBitmask: 1),
    821: City(name: "Istanbul", country: "Turkey", imageName: "istanbul_pic", latitude: 41.0082, longitude: 28.9784, description: "Magical bridge between East and West along the Bosphorus Strait.", sceneryBitmask: 5),
    825: City(name: "Marmaris", country: "Turkey", imageName: "marmaris_pic", latitude: 36.8523, longitude: 28.2740, description: "Popular harbor and beach resort on the Turkish coast.", sceneryBitmask: 5),
    827: City(name: "Side", country: "Turkey", imageName: "side_pic", latitude: 36.7667, longitude: 31.3889, description: "Ancient Turkish port city rich in Roman temples and beaches.", sceneryBitmask: 5),
    829: City(name: "Bukovel", country: "Ukraine", imageName: "bukovel_pic", latitude: 48.3533, longitude: 24.4128, description: "The premier ski resort of the Ukrainian Carpathians.", sceneryBitmask: 8),
    831: City(name: "Kiev", country: "Ukraine", imageName: "kiev_pic", latitude: 50.4501, longitude: 30.5234, description: "Historic and monumental Ukrainian capital along the Dnipro River.", sceneryBitmask: 1),
    832: City(name: "Lviv", country: "Ukraine", imageName: "lviv_pic", latitude: 49.8397, longitude: 24.0297, description: "Architectural jewel of western Ukraine, famous for coffee and culture.", sceneryBitmask: 1),
    833: City(name: "Odessa", country: "Ukraine", imageName: "odessa_pic", latitude: 46.4825, longitude: 30.7233, description: "The Pearl of the Black Sea, celebrated for historic stairs and lively atmosphere.", sceneryBitmask: 5),
    834: City(name: "Zhytomyr", country: "Ukraine", imageName: "zhytomyr_pic", latitude: 50.2547, longitude: 28.6587, description: "Historic green city surrounded by forests and rivers.", sceneryBitmask: 2),
    846: City(name: "London", country: "United Kingdom", imageName: "london_pic", latitude: 51.5074, longitude: -0.1278, description: "Global British capital offering free museums, history, and modernity.", sceneryBitmask: 1),
    848: City(name: "Oxford", country: "United Kingdom", imageName: "oxford_pic", latitude: 51.7520, longitude: -1.2577, description: "Prestigious and historic English university city with legendary spires.", sceneryBitmask: 1),
    851: City(name: "Gibraltar", country: "United Kingdom", imageName: "gibraltar_pic", latitude: 36.1408, longitude: -5.3536, description: "Famous British promontory at the southern tip of the Iberian Peninsula.", sceneryBitmask: 13),
    853: City(name: "Derry", country: "United Kingdom", imageName: "derry_pic", latitude: 54.9966, longitude: -7.3086, description: "Historic walled city in Northern Ireland.", sceneryBitmask: 5),
    863: City(name: "Tenby", country: "United Kingdom", imageName: "tenby_pic", latitude: 51.6727, longitude: -4.6989, description: "Picturesque and colorful Welsh coastal village.", sceneryBitmask: 5)
]
